config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :authors
  resources :books
  root 'home#index'
  Rails.application.routes.draw do
    # Outras rotas
    get 'switch_locale', to: 'application#switch_locale', as: :switch_locale
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, dependent: :destroy
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    if params[:locale]
      cookies[:locale] = params[:locale]
    end

    if cookies[:locale]
      if I18n.locale != cookies[:locale].to_sym
        I18n.locale = cookies[:locale].to_sym
      end
    end 
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show edit update destroy ]

  # GET /authors or /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1 or /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors or /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to author_url(@author), notice: "Author was successfully created." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1 or /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to author_url(@author), notice: "Author was successfully updated." }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1 or /authors/1.json
  def destroy
    @author.destroy!

    respond_to do |format|
      format.html { redirect_to authors_url, notice: "Author was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:description, :age, :country)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :set_author_options, only: %i[ new create edit update ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy!

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_author_options
      @author_options = Author.all.pluck(:description, :id)
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:description, :year, :pages, :author_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/authors/_author.html.erb
<div id="<%= dom_id author %>" class="card bg-dark text-white mb-3">
  <div class="card-header">
    <h3 class="card-title"><%= author.description %></h3>
  </div>
  <div class="card-body">
    <div class="form-group row">
      <label for="staticDescription" class="col-sm-2 col-form-label"><strong><%= t("author_name")%></strong></label>
      <div class="col-sm-10">
        <input type="text" readonly class="form-control-plaintext text-white" id="staticDescription" value="<%= author.description %>">
      </div>
    </div>

    <div class="form-group row">
      <label for="staticAge" class="col-sm-2 col-form-label"><strong><%=t("author_age")%></strong></label>
      <div class="col-sm-10">
        <input type="text" readonly class="form-control-plaintext text-white" id="staticAge" value="<%= author.age %>">
      </div>
    </div>

    <div class="form-group row">
      <label for="staticCountry" class="col-sm-2 col-form-label"><strong><%=t("author_country")%></strong></label>
      <div class="col-sm-10">
        <input type="text" readonly class="form-control-plaintext text-white" id="staticCountry" value="<%= author.country %>">
      </div>
    </div>

    <div class="form-group row">
      <label for="staticBooks" class="col-sm-2 col-form-label"><strong><%=t("author_books")%></strong></label>
      <div class="col-sm-10">
        <ul class="list-unstyled">
          <% author.books.each do |book| %>
            <li class="text-danger"><%= book.description %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/authors/_form.html.erb
<%= form_with(model: author) do |form| %>
  <% if author.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <span class="text-white"><%= form.label :description, style: "display: block" %>
    <%= form.text_field :description, class:"form-control", placeholder:"Author name" %>
  </div>

  <div class="form-group">
    <span class="text-white"><%= form.label :age, style: "display: block" %>
    <%= form.number_field :age, class:"form-control", placeholder:"Author age" %>
  </div>

  <div class="form-group">
    <span class="text-white"><%= form.label :country, style: "display: block" %>
    <%= form.text_field :country, class:"form-control", placeholder:"Author country" %>
  </div><br>

  <div>
    <%= form.submit nil, class: "btn btn-primary btn-lg" %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<span class="text-white"><h1>Editing author</h1>

<%= render "form", author: @author %>

<br>

<div>
  <%= link_to "Show this author", @author %> |
  <%= link_to "Back to authors", authors_path %>
</div>

app/views/authors/index.html.erb
<span class="text-white"><h1>Authors</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Description</th>
      <th>Age</th>
      <th>Country</th>
      <th>Books</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.description %></td>
        <td><%= author.age %></td>
        <td><%= author.country %></td>
        <td>
          <ul>
            <% author.books.each do |book| %>
              <li><%= book.description %></li>
            <% end %>
          </ul>
        </td>
        <td>
          <%= link_to "Show", author, class: "btn btn-primary btn-sm" %>
          <%= link_to "Edit", edit_author_path(author), class: "btn btn-primary btn-sm" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<p class="lead">
  <%= link_to "New Author", new_author_path, class: "btn btn-primary btn-sml" %>
</p>

app/views/authors/new.html.erb
<span class="text-white"><h1>New Author</h1>

<%= render "form", author: @author %>

<br>

<div>
  <%= link_to "Back", authors_path, class: "btn btn-primary btn-lg" %>
</div>

app/views/authors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @author %>

<div>
  <%= link_to "Edit this author", edit_author_path(@author) %> |
  <%= link_to "Back to authors", authors_path %>

  <%= button_to "Destroy this author", @author, method: :delete %>
</div>

app/views/books/_book.html.erb
<div id="<%= dom_id book %>" class="card bg-dark text-white mb-3">
  <div class="card-header">
    <h3 class="card-title"><%= book.description %></h3>
  </div>
  <div class="card-body">
    <form>
      <div class="form-group row">
        <label for="staticDescription" class="col-sm-2 col-form-label"><strong>Description:</strong></label>
        <div class="col-sm-10">
          <input type="text" readonly class="form-control-plaintext text-white" id="staticDescription" value="<%= book.description %>">
        </div>
      </div>

      <div class="form-group row">
        <label for="staticYear" class="col-sm-2 col-form-label"><strong>Year:</strong></label>
        <div class="col-sm-10">
          <input type="text" readonly class="form-control-plaintext text-white" id="staticYear" value="<%= book.year %>">
        </div>
      </div>

      <div class="form-group row">
        <label for="staticPages" class="col-sm-2 col-form-label"><strong>Pages:</strong></label>
        <div class="col-sm-10">
          <input type="text" readonly class="form-control-plaintext text-white" id="staticPages" value="<%= book.pages %>">
        </div>
      </div>

      <div class="form-group row">
        <label for="staticAuthor" class="col-sm-2 col-form-label"><strong>Author:</strong></label>
        <div class="col-sm-10">
          <input type="text" readonly class="form-control-plaintext text-danger" id="staticAuthor" value="<%= book.author.description %>">
        </div>
      </div>
    </form>
  </div>
</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <span class="text-white"><%= form.label :description, style: "display: block" %>
    <%= form.text_field :description, class:"form-control", placeholder:"Book name" %>
  </div>

  <div class="form-group">
    <span class="text-white"><%= form.label :year, style: "display: block" %>
    <%= form.number_field :year, class:"form-control", placeholder:"Release year" %>
  </div>

  <div class="form-group">
    <span class="text-white"><%= form.label :pages, style: "display: block" %>
    <%= form.number_field :pages, class:"form-control", placeholder:"How many pages?" %>
  </div>

  <div class="form-group">
    <span class="text-white"><%= form.label :author_id, style: "display: block" %>
    <%= form.select("author_id", @author_options, {include_blank: true}, class:"form-control") %>
  </div><br>

  <div>
    <%= form.submit nil, class: "btn btn-primary btn-lg"  %>
  </div>
<% end %>

app/views/books/edit.html.erb
<span class="text-white"><h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<span class="text-white"><h1>Books</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Book Name</th>
      <th>Year</th>
      <th>Pages</th>
      <th>Author</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.description %></td>
        <td><%= book.year %></td>
        <td><%= book.pages %></td>
        <td><%= book.author.description %></td>
        <td>
          <%= link_to "Show", book, class: "btn btn-primary btn-sm" %>
          <%= link_to "Edit", edit_book_path(book), class: "btn btn-primary btn-sm" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<p class="lead">
  <%= link_to "New Book", new_book_path, class: "btn btn-primary btn-sml" %>
</p>

app/views/books/new.html.erb
<span class="text-white"><h1>New Book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<div>
  <%= link_to "Edit this book", edit_book_path(@book) %> |
  <%= link_to "Back to books", books_path %>

  <%= button_to "Destroy this book", @book, method: :delete %>
</div>

app/views/home/index.html.erb
<div class="lead text-white jumbotron">
  <h1 class="display-4"><%= t("hello")%></h1>
  <p class="lead"><%= t("intro_text")%></p>
  <hr class="my-4">
  <p><%= t("intro_select")%></p>
  <p class="lead">
    <%= link_to "New Book", new_book_path, class: "btn btn-primary btn-lg" %>
    <%= link_to "New Author", new_author_path, class: "btn btn-primary btn-lg" %>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuthorLink</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>

</head>

<body>
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
    <div class="container-fluid">
      <a class="navbar-brand">AuthorLink</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Books", books_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Authors", authors_path, class: "nav-link" %>
          </li>
        </ul>
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "pt-BR", root_path(locale: 'pt-BR'), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "en", root_path(locale: 'en'), class: "nav-link" %>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container mt-4">
    <%= yield %>
  </div>

</body>
</html>